replicaCount: 1

environment: prod

image:
        name: wallet-next
        repo: threefoldjimber/wallet-next
        tag: 19022765a78b7482f97ab15b4ab914835e1c7e02 
        containerPort: 80

service:
        port: 80
        targetPort: 80

ingress:
        hosts:
                - name: wallet-next.threefold.me
                  path: /
                  service: wallet-next-prod
                  port: 80


                  

acme:
        email: laudr1997@gmail.com

secrets:
        FLAGSMITH_ENVIROMENT_KEY: S5j22oQHTzUk7y4khnBxda
