apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "releaseName" . }}
  name:  {{ template "releaseName" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ template "releaseName" . }}
  type: ClusterIP
status:
  loadBalancer: {}
